---
- name: Download and Extract 
  ansible.builtin.unarchive:
    ##    https://releases.hashicorp.com/consul/1.10.2/consul_1.10.2_linux_armhfv6.zip
    src: "https://releases.hashicorp.com/consul/{{ consul__version }}/consul_{{ consul__version }}_linux_armhfv6.zip"
    dest: /usr/bin
    remote_src: yes
  notify:
    - restart consul

- name: Ensure /etc/consul.d file system exists
  file: 
    path: "{{ consul__config_path }}"
    group: root
    owner: root
    state: directory

- name: Ensure /opt/consul file system exists
  file: 
    path: /opt/consul
    group: consul
    owner: consul
    state: directory

- name: Configure
  template:
    src: consul.hcl.j2
    dest: "{{ consul__config_path }}/consul.hcl"
  notify: restart consul

- name: Validate consul config
  command: consul validate "{{ consul__config_path }}/"
  changed_when: false

- name: Configure unit file for systemd
  template:
    src: consul_systemd.service.hcl.j2
    dest: /usr/lib/systemd/system/consul.service
    owner: root
    group: root
    mode: 0644
  notify: restart consul

- name: Ensure service is running
  systemd:
    name: consul
    state: started
    enabled: true

- name: Run handlers
  meta: flush_handlers
