---
- name: Add repository
  yum_repository:
    name: hashicorp
    description: Hashicorp Repo
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgcheck: true
    gpgkey: https://rpm.releases.hashicorp.com/gpg
