---
- name: Register/De-register services
  community.general.consul:
    service_name: "{{ item.service_name | default(omit) }}"
    service_port: "{{ item.service_port | default(omit) }}"
    service_address: "{{ item.service_address | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    tags: "{{ item.tags | default(omit) }}"
    check_name: "{{ item.check_name | default(omit) }}"
    notes: "{{ item.notes | default(omit) }}"
    script: "{{ item.script | default(omit) }}"
    timeout: "{{ item.timeout | default(omit) }}"
    ttl: "{{ item.ttl | default(omit) }}"
    tcp: "{{ item.tcp | default(omit) }}"
    http: "{{ item.http | default(omit) }}"
  with_items: "{{ consul_service__services }}"
