---
vault__package: "vault"
#vault__node_name: "{{ inventory_hostname_short }}"
#vault__log_level: INFO
#vault__data_path: /opt/vault/data
#vault__roles:
#  - client
#  - server

#vault__bind_address: "0.0.0.0"
#vault__advertise_address: "{{ ansible_default_ipv4.address }}"

#vault__node_class: ""

#vault__datacenter: "{{ hashi_common__datacenter }}"
#vault__region: "global"

#vault__port_http: 4646
#vault__port_rpc: 4647
#vault__port_serf: 4648

#vault__telemetry_collection_interval: 60s

# Ansible Inventory Vault Group Name of Servers
#vault__server_group_name: vault_servers

# See https://www.vaultproject.io/docs/configuration/server#configuring-scheduler-config for limitations
#vault__server__default_scheduler_config_scheduler_algorithm: "binpack"

vault__use_consul: false

vault__client_meta: {}
vault__client_network_interface: null

# Reserved resources
vault__client_reserved_cpu: 200
vault__client_reserved_memory: 256
vault__client_reserved_disk: 1024
vault__client_reserved_ports:
  - "22"
  - "8500-8600"

# Host volumes
vault__client_host_volume_basepath: "/mnt"
vault__client_host_volumes: []
#  - name: mysql
#    path: /mysql

# Host networks
vault__client_host_networks: []
  # - name: public
  #   cidr: "203.0.113.0/24"

## Plugins configs
# docker
vault__client_plugin_docker_allow_privileged: false
vault__client_plugin_docker_volume_enabled: true
# raw_exec
vault__client_plugin_raw_exec_enabled: false
